const tools = [

  // ─── MAJOR AI ASSISTANTS ─────────────────────────────────────────────────────
  {
    name: "ChatGPT",
    desc: "AI chatbot by OpenAI for writing, coding & reasoning",
    img: "https://www.google.com/s2/favicons?sz=64&domain=chat.openai.com",
    category: "chatbot, writing, coding",
    link: "https://chat.openai.com",
  },
  {
    name: "Claude",
    desc: "Anthropic's AI assistant — top-ranked for coding & analysis",
    img: "https://www.google.com/s2/favicons?sz=64&domain=claude.ai",
    category: "chatbot, writing, coding",
    link: "https://claude.ai",
  },
  {
    name: "Gemini",
    desc: "Google's multimodal AI for writing, coding & research",
    img: "https://www.google.com/s2/favicons?sz=64&domain=gemini.google.com",
    category: "chatbot, writing, coding",
    link: "https://gemini.google.com",
  },
  {
    name: "DeepSeek",
    desc: "Powerful open-source AI model for coding & reasoning",
    img: "https://www.google.com/s2/favicons?sz=64&domain=deepseek.com",
    category: "chatbot, coding",
    link: "https://deepseek.com",
  },
  {
    name: "Grok",
    desc: "xAI's conversational AI built into X (Twitter)",
    img: "https://www.google.com/s2/favicons?sz=64&domain=x.ai",
    category: "chatbot, writing",
    link: "https://x.ai",
  },
  {
    name: "Meta AI",
    desc: "Meta's Llama-powered AI assistant across apps",
    img: "https://www.google.com/s2/favicons?sz=64&domain=meta.ai",
    category: "chatbot, writing",
    link: "https://meta.ai",
  },
  {
    name: "Mistral AI",
    desc: "Open-weight European AI for chat and coding",
    img: "https://www.google.com/s2/favicons?sz=64&domain=mistral.ai",
    category: "chatbot, coding",
    link: "https://mistral.ai",
  },
  {
    name: "Perplexity AI",
    desc: "AI-powered search engine with cited, sourced answers",
    img: "https://www.google.com/s2/favicons?sz=64&domain=perplexity.ai",
    category: "chatbot, research",
    link: "https://perplexity.ai",
  },
  {
    name: "Cohere",
    desc: "Enterprise AI for text understanding and generation",
    img: "https://www.google.com/s2/favicons?sz=64&domain=cohere.com",
    category: "chatbot, writing",
    link: "https://cohere.com",
  },
  {
    name: "You.com",
    desc: "AI search assistant combining web results and chat",
    img: "https://www.google.com/s2/favicons?sz=64&domain=you.com",
    category: "chatbot, research",
    link: "https://you.com",
  },

  // ─── AI CODING TOOLS ─────────────────────────────────────────────────────────
  {
    name: "GitHub Copilot",
    desc: "AI coding assistant built into VS Code & JetBrains",
    img: "https://www.google.com/s2/favicons?sz=64&domain=github.com",
    category: "coding",
    link: "https://github.com/features/copilot",
  },
  {
    name: "Cursor",
    desc: "AI-first IDE for multi-file editing and codebase chat",
    img: "https://www.google.com/s2/favicons?sz=64&domain=cursor.com",
    category: "coding",
    link: "https://cursor.com",
  },
  {
    name: "Claude Code",
    desc: "Terminal AI agent by Anthropic — #1 on SWE-bench 2026",
    img: "https://www.google.com/s2/favicons?sz=64&domain=claude.ai",
    category: "coding",
    link: "https://claude.ai/code",
  },
  {
    name: "Replit AI",
    desc: "AI coding platform with browser-based IDE and deployment",
    img: "https://www.google.com/s2/favicons?sz=64&domain=replit.com",
    category: "coding",
    link: "https://replit.com",
  },
  {
    name: "Windsurf",
    desc: "AI-native IDE with agentic multi-file code editing",
    img: "https://www.google.com/s2/favicons?sz=64&domain=codeium.com",
    category: "coding",
    link: "https://codeium.com/windsurf",
  },
  {
    name: "Codeium",
    desc: "Free AI code completion for 70+ programming languages",
    img: "https://www.google.com/s2/favicons?sz=64&domain=codeium.com",
    category: "coding",
    link: "https://codeium.com",
  },
  {
    name: "Tabnine",
    desc: "Privacy-first AI code completion with on-premise support",
    img: "https://www.google.com/s2/favicons?sz=64&domain=tabnine.com",
    category: "coding",
    link: "https://tabnine.com",
  },
  {
    name: "Amazon Q",
    desc: "AWS AI developer assistant for cloud coding & deployment",
    img: "https://www.google.com/s2/favicons?sz=64&domain=aws.amazon.com",
    category: "coding",
    link: "https://aws.amazon.com/q/developer",
  },
  {
    name: "Gemini Code Assist",
    desc: "Google's AI code completion for VS Code and JetBrains",
    img: "https://www.google.com/s2/favicons?sz=64&domain=gemini.google.com",
    category: "coding",
    link: "https://cloud.google.com/gemini/docs/codeassist",
  },
  {
    name: "Lovable",
    desc: "AI full-stack app builder from natural language prompts",
    img: "https://www.google.com/s2/favicons?sz=64&domain=lovable.dev",
    category: "coding",
    link: "https://lovable.dev",
  },
  {
    name: "Bolt.new",
    desc: "AI web app builder with instant live preview in browser",
    img: "https://www.google.com/s2/favicons?sz=64&domain=bolt.new",
    category: "coding",
    link: "https://bolt.new",
  },
  {
    name: "v0 by Vercel",
    desc: "AI UI component generator using shadcn & Tailwind",
    img: "https://www.google.com/s2/favicons?sz=64&domain=v0.dev",
    category: "coding",
    link: "https://v0.dev",
  },
  {
    name: "Aider",
    desc: "Open-source terminal AI coding agent for Git projects",
    img: "https://www.google.com/s2/favicons?sz=64&domain=aider.chat",
    category: "coding",
    link: "https://aider.chat",
  },
  {
    name: "Devin",
    desc: "Autonomous AI software engineer by Cognition AI",
    img: "https://www.google.com/s2/favicons?sz=64&domain=cognition.ai",
    category: "coding",
    link: "https://cognition.ai",
  },
  {
    name: "Qodo",
    desc: "AI code review and pull request validation platform",
    img: "https://www.google.com/s2/favicons?sz=64&domain=qodo.ai",
    category: "coding",
    link: "https://qodo.ai",
  },
  {
    name: "Sourcegraph Cody",
    desc: "AI coding assistant with full codebase context and search",
    img: "https://www.google.com/s2/favicons?sz=64&domain=sourcegraph.com",
    category: "coding",
    link: "https://sourcegraph.com/cody",
  },
  {
    name: "JetBrains AI",
    desc: "AI assistant built into IntelliJ, PyCharm & WebStorm IDEs",
    img: "https://www.google.com/s2/favicons?sz=64&domain=jetbrains.com",
    category: "coding",
    link: "https://jetbrains.com/ai",
  },
  {
    name: "Zed",
    desc: "Lightning-fast AI code editor with real-time collaboration",
    img: "https://www.google.com/s2/favicons?sz=64&domain=zed.dev",
    category: "coding",
    link: "https://zed.dev",
  },
  {
    name: "Manus AI",
    desc: "Autonomous AI agent for end-to-end software development",
    img: "https://www.google.com/s2/favicons?sz=64&domain=manus.im",
    category: "coding",
    link: "https://manus.im",
  },
  {
    name: "Snyk Code",
    desc: "AI-powered security vulnerability scanning for developers",
    img: "https://www.google.com/s2/favicons?sz=64&domain=snyk.io",
    category: "coding",
    link: "https://snyk.io",
  },
  {
    name: "Durable AI",
    desc: "AI website builder — from prompt to live site in seconds",
    img: "https://www.google.com/s2/favicons?sz=64&domain=durable.co",
    category: "coding, development",
    link: "https://durable.co",
  },
  {
    name: "Framer AI",
    desc: "AI-powered no-code website design and publishing",
    img: "https://www.google.com/s2/favicons?sz=64&domain=framer.com",
    category: "coding, development",
    link: "https://framer.com",
  },
  {
    name: "10Web AI",
    desc: "AI WordPress website builder with auto-optimization",
    img: "https://www.google.com/s2/favicons?sz=64&domain=10web.io",
    category: "coding, development",
    link: "https://10web.io",
  },
  {
    name: "FEmesh",
    desc: "Desktop meshing software for FEA and CFD simulation",
    img: "https://www.google.com/s2/favicons?sz=64&domain=femesh.com",
    category: "coding, development",
    link: "https://femesh.com",
  },

  // ─── WRITING TOOLS ───────────────────────────────────────────────────────────
  {
    name: "Jasper AI",
    desc: "AI content writing tool for marketing and long-form blogs",
    img: "https://www.google.com/s2/favicons?sz=64&domain=jasper.ai",
    category: "writing",
    link: "https://jasper.ai",
  },
  {
    name: "Copy.ai",
    desc: "AI copywriting assistant for ads, emails and social content",
    img: "https://www.google.com/s2/favicons?sz=64&domain=copy.ai",
    category: "writing",
    link: "https://copy.ai",
  },
  {
    name: "Grammarly AI",
    desc: "AI grammar, tone and writing style assistant",
    img: "https://www.google.com/s2/favicons?sz=64&domain=grammarly.com",
    category: "writing",
    link: "https://grammarly.com",
  },
  {
    name: "Quillbot",
    desc: "AI paraphrasing, summarizing and grammar checking tool",
    img: "https://www.google.com/s2/favicons?sz=64&domain=quillbot.com",
    category: "writing",
    link: "https://quillbot.com",
  },
  {
    name: "DeepL",
    desc: "AI translation tool with near-human language accuracy",
    img: "https://www.google.com/s2/favicons?sz=64&domain=deepl.com",
    category: "writing",
    link: "https://deepl.com",
  },
  {
    name: "Wordtune",
    desc: "AI tool to intelligently rewrite and improve sentences",
    img: "https://www.google.com/s2/favicons?sz=64&domain=wordtune.com",
    category: "writing",
    link: "https://wordtune.com",
  },
  {
    name: "Rytr",
    desc: "Affordable AI writing assistant for all content types",
    img: "https://www.google.com/s2/favicons?sz=64&domain=rytr.me",
    category: "writing",
    link: "https://rytr.me",
  },
  {
    name: "Sudowrite",
    desc: "AI creative writing and fiction drafting companion",
    img: "https://www.google.com/s2/favicons?sz=64&domain=sudowrite.com",
    category: "writing",
    link: "https://sudowrite.com",
  },
  {
    name: "Writesonic",
    desc: "AI writing platform with chatbot, SEO and content tools",
    img: "https://www.google.com/s2/favicons?sz=64&domain=writesonic.com",
    category: "writing",
    link: "https://writesonic.com",
  },

  // ─── DESIGN TOOLS ────────────────────────────────────────────────────────────
  {
    name: "Midjourney",
    desc: "Generate stunning AI art and images from text prompts",
    img: "https://www.google.com/s2/favicons?sz=64&domain=midjourney.com",
    category: "design",
    link: "https://midjourney.com",
  },
  {
    name: "Canva AI",
    desc: "AI-powered design tool for graphics and presentations",
    img: "https://www.google.com/s2/favicons?sz=64&domain=canva.com",
    category: "design",
    link: "https://canva.com",
  },
  {
    name: "Leonardo AI",
    desc: "Professional AI image and art generator for creatives",
    img: "https://www.google.com/s2/favicons?sz=64&domain=leonardo.ai",
    category: "design",
    link: "https://leonardo.ai",
  },
  {
    name: "DALL·E",
    desc: "OpenAI's AI image generator from text descriptions",
    img: "https://www.google.com/s2/favicons?sz=64&domain=openai.com",
    category: "design",
    link: "https://openai.com/dall-e",
  },
  {
    name: "Adobe Firefly",
    desc: "Adobe's generative AI for images, text effects & vectors",
    img: "https://www.google.com/s2/favicons?sz=64&domain=firefly.adobe.com",
    category: "design",
    link: "https://firefly.adobe.com",
  },
  {
    name: "Stable Diffusion",
    desc: "Open-source AI image generation model by Stability AI",
    img: "https://www.google.com/s2/favicons?sz=64&domain=stability.ai",
    category: "design",
    link: "https://stability.ai",
  },
  {
    name: "Ideogram",
    desc: "AI image generator with accurate text-in-image rendering",
    img: "https://www.google.com/s2/favicons?sz=64&domain=ideogram.ai",
    category: "design",
    link: "https://ideogram.ai",
  },
  {
    name: "Flux AI",
    desc: "High-quality open-source AI image model by Black Forest Labs",
    img: "https://www.google.com/s2/favicons?sz=64&domain=blackforestlabs.ai",
    category: "design",
    link: "https://blackforestlabs.ai",
  },
  {
    name: "Remove.bg",
    desc: "Instantly remove image backgrounds with AI precision",
    img: "https://www.google.com/s2/favicons?sz=64&domain=remove.bg",
    category: "design",
    link: "https://remove.bg",
  },
  {
    name: "Looka",
    desc: "AI-powered logo maker and brand identity builder",
    img: "https://www.google.com/s2/favicons?sz=64&domain=looka.com",
    category: "design",
    link: "https://looka.com",
  },
  {
    name: "Uizard",
    desc: "AI UI/UX design tool for wireframes and app mockups",
    img: "https://www.google.com/s2/favicons?sz=64&domain=uizard.io",
    category: "design",
    link: "https://uizard.io",
  },

  // ─── VIDEO TOOLS ─────────────────────────────────────────────────────────────
  {
    name: "Runway ML",
    desc: "Professional AI video editing and generation platform",
    img: "https://www.google.com/s2/favicons?sz=64&domain=runwayml.com",
    category: "video",
    link: "https://runwayml.com",
  },
  {
    name: "Sora",
    desc: "OpenAI's text-to-video AI model for cinematic clips",
    img: "https://www.google.com/s2/favicons?sz=64&domain=openai.com",
    category: "video",
    link: "https://openai.com/sora",
  },
  {
    name: "Kling AI",
    desc: "High-quality AI video generation by Kuaishou",
    img: "https://www.google.com/s2/favicons?sz=64&domain=klingai.com",
    category: "video",
    link: "https://klingai.com",
  },
  {
    name: "HeyGen",
    desc: "AI video generator with lifelike talking avatar presenters",
    img: "https://www.google.com/s2/favicons?sz=64&domain=heygen.com",
    category: "video",
    link: "https://heygen.com",
  },
  {
    name: "Synthesia",
    desc: "Create AI avatar presentation videos at scale",
    img: "https://www.google.com/s2/favicons?sz=64&domain=synthesia.io",
    category: "video",
    link: "https://synthesia.io",
  },
  {
    name: "Pictory",
    desc: "Turn scripts and blog posts into short AI videos",
    img: "https://www.google.com/s2/favicons?sz=64&domain=pictory.ai",
    category: "video",
    link: "https://pictory.ai",
  },
  {
    name: "Descript",
    desc: "Edit audio and video by simply editing the text transcript",
    img: "https://www.google.com/s2/favicons?sz=64&domain=descript.com",
    category: "video",
    link: "https://descript.com",
  },
  {
    name: "Lumen5",
    desc: "AI video creation from blog posts and written content",
    img: "https://www.google.com/s2/favicons?sz=64&domain=lumen5.com",
    category: "video",
    link: "https://lumen5.com",
  },
  {
    name: "Kapwing AI",
    desc: "Online AI-powered video editor with team collaboration",
    img: "https://www.google.com/s2/favicons?sz=64&domain=kapwing.com",
    category: "video",
    link: "https://kapwing.com",
  },
  {
    name: "Invideo AI",
    desc: "AI text-to-video creator with voiceover and auto-editing",
    img: "https://www.google.com/s2/favicons?sz=64&domain=invideo.io",
    category: "video",
    link: "https://invideo.io",
  },

  // ─── PRODUCTIVITY TOOLS ──────────────────────────────────────────────────────
  {
    name: "Notion AI",
    desc: "AI writing and summarization built into Notion docs",
    img: "https://www.google.com/s2/favicons?sz=64&domain=notion.so",
    category: "productivity",
    link: "https://notion.so",
  },
  {
    name: "Microsoft Copilot",
    desc: "AI assistant woven across all Microsoft 365 Office apps",
    img: "https://www.google.com/s2/favicons?sz=64&domain=copilot.microsoft.com",
    category: "productivity",
    link: "https://copilot.microsoft.com",
  },
  {
    name: "Gamma AI",
    desc: "AI-generated presentations, docs and mini-websites",
    img: "https://www.google.com/s2/favicons?sz=64&domain=gamma.app",
    category: "productivity",
    link: "https://gamma.app",
  },
  {
    name: "Tome AI",
    desc: "AI-powered narrative presentation and storytelling tool",
    img: "https://www.google.com/s2/favicons?sz=64&domain=tome.app",
    category: "productivity",
    link: "https://tome.app",
  },
  {
    name: "Fireflies AI",
    desc: "AI meeting transcription, notes and action item tracker",
    img: "https://www.google.com/s2/favicons?sz=64&domain=fireflies.ai",
    category: "productivity",
    link: "https://fireflies.ai",
  },
  {
    name: "Otter AI",
    desc: "Real-time AI transcription and meeting summary tool",
    img: "https://www.google.com/s2/favicons?sz=64&domain=otter.ai",
    category: "productivity",
    link: "https://otter.ai",
  },
  {
    name: "Taskade AI",
    desc: "AI-powered task manager and collaborative team workspace",
    img: "https://www.google.com/s2/favicons?sz=64&domain=taskade.com",
    category: "productivity",
    link: "https://taskade.com",
  },
  {
    name: "ClickUp AI",
    desc: "All-in-one AI productivity and project management platform",
    img: "https://www.google.com/s2/favicons?sz=64&domain=clickup.com",
    category: "productivity",
    link: "https://clickup.com",
  },
  {
    name: "Motion AI",
    desc: "AI calendar that auto-schedules tasks and meetings",
    img: "https://www.google.com/s2/favicons?sz=64&domain=usemotion.com",
    category: "productivity",
    link: "https://usemotion.com",
  },
  {
    name: "Zapier AI",
    desc: "AI workflow automation connecting 6,000+ apps and services",
    img: "https://www.google.com/s2/favicons?sz=64&domain=zapier.com",
    category: "productivity",
    link: "https://zapier.com",
  },

  // ─── AUDIO TOOLS ─────────────────────────────────────────────────────────────
  {
    name: "ElevenLabs",
    desc: "Hyper-realistic AI voice cloning and text-to-speech",
    img: "https://www.google.com/s2/favicons?sz=64&domain=elevenlabs.io",
    category: "audio",
    link: "https://elevenlabs.io",
  },
  {
    name: "Murf AI",
    desc: "Studio-quality AI voiceovers for videos and podcasts",
    img: "https://www.google.com/s2/favicons?sz=64&domain=murf.ai",
    category: "audio",
    link: "https://murf.ai",
  },
  {
    name: "PlayHT",
    desc: "Ultra-realistic AI text-to-speech with voice cloning",
    img: "https://www.google.com/s2/favicons?sz=64&domain=play.ht",
    category: "audio",
    link: "https://play.ht",
  },
  {
    name: "Suno AI",
    desc: "Generate full original AI songs with vocals from text",
    img: "https://www.google.com/s2/favicons?sz=64&domain=suno.com",
    category: "audio",
    link: "https://suno.com",
  },
  {
    name: "Udio",
    desc: "AI music generation tool for professional-sounding tracks",
    img: "https://www.google.com/s2/favicons?sz=64&domain=udio.com",
    category: "audio",
    link: "https://udio.com",
  },
  {
    name: "Soundraw",
    desc: "AI royalty-free music generator for creators and videos",
    img: "https://www.google.com/s2/favicons?sz=64&domain=soundraw.io",
    category: "audio",
    link: "https://soundraw.io",
  },
  {
    name: "Boomy",
    desc: "Create and publish original AI-generated music tracks",
    img: "https://www.google.com/s2/favicons?sz=64&domain=boomy.com",
    category: "audio",
    link: "https://boomy.com",
  },
];