// const tools = [
//   {
//     name: "aiselfi.es",
//     desc: "Convierte selfies en fotos profesionales con IA.",
//     img: "image/logo.png",
//   },
//   {
//     name: "ChatGPT",
//     desc: "AI chatbot for writing and coding",
//     img: "image/logo.png",
//   },
// ];

const tools = [
  {
    name: "ChatGPT",
    desc: "AI chatbot for writing and coding",
    img: "image/logo.png",
    category: "ChatGPT, writing",
    link: "https://chat.openai.com",
  },
  {
    name: "Midjourney",
    desc: "Generate AI images from text",
    img: "image/logo.png",
    category: "design",
    link: "https://midjourney.com",
  },
  {
    name: "Canva AI",
    desc: "AI-powered design tool",
    img: "image/logo.png",
    category: "design",
    link: "https://canva.com",
  },
  {
    name: "Notion AI",
    desc: "AI notes and productivity tool",
    img: "image/logo.png",
    category: "productivity",
    link: "https://notion.so",
  },
  {
    name: "Jasper AI",
    desc: "AI content writing tool",
    img: "image/logo.png",
    category: "writing",
    link: "https://jasper.ai",
  },
  {
    name: "Copy.ai",
    desc: "AI copywriting assistant",
    img: "image/logo.png",
    category: "writing",
    link: "https://copy.ai",
  },
  {
    name: "Grammarly AI",
    desc: "Grammar and writing assistant",
    img: "image/logo.png",
    category: "writing",
    link: "https://grammarly.com",
  },
  {
    name: "Quillbot",
    desc: "Paraphrasing AI tool",
    img: "image/logo.png",
    category: "writing",
    link: "https://quillbot.com",
  },
  {
    name: "Tome AI",
    desc: "AI presentation generator",
    img: "image/logo.png",
    category: "productivity",
    link: "https://tome.app",
  },
  {
    name: "Runway ML",
    desc: "AI video editing tool",
    img: "image/logo.png",
    category: "video",
    link: "https://runwayml.com",
  },

  {
    name: "Pictory",
    desc: "Text to video AI tool",
    img: "image/logo.png",
    category: "video",
    link: "https://pictory.ai",
  },
  {
    name: "Synthesia",
    desc: "AI avatar video generator",
    img: "image/logo.png",
    category: "video",
    link: "https://synthesia.io",
  },
  {
    name: "Lumen5",
    desc: "AI video creation platform",
    img: "image/logo.png",
    category: "video",
    link: "https://lumen5.com",
  },
  {
    name: "Descript",
    desc: "Audio and video editing AI tool",
    img: "image/logo.png",
    category: "video",
    link: "https://descript.com",
  },
  {
    name: "Kapwing AI",
    desc: "Online AI video editor",
    img: "image/logo.png",
    category: "video",
    link: "https://kapwing.com",
  },

  {
    name: "Leonardo AI",
    desc: "AI art generator",
    img: "image/logo.png",
    category: "design",
    link: "https://leonardo.ai",
  },
  {
    name: "DALL·E",
    desc: "AI image generator by OpenAI",
    img: "image/logo.png",
    category: "design",
    link: "https://openai.com",
  },
  {
    name: "Remove.bg",
    desc: "Remove image background",
    img: "image/logo.png",
    category: "design",
    link: "https://remove.bg",
  },
  {
    name: "Looka",
    desc: "AI logo maker",
    img: "image/logo.png",
    category: "design",
    link: "https://looka.com",
  },
  {
    name: "Uizard",
    desc: "AI UI design tool",
    img: "image/logo.png",
    category: "design",
    link: "https://uizard.io",
  },

  {
    name: "Durable AI",
    desc: "AI website builder",
    img: "image/logo.png",
    category: "development",
    link: "https://durable.co",
  },
  {
    name: "Framer AI",
    desc: "AI website builder tool",
    img: "image/logo.png",
    category: "development",
    link: "https://framer.com",
  },
  {
    name: "10Web AI",
    desc: "AI WordPress builder",
    img: "image/logo.png",
    category: "development",
    link: "https://10web.io",
  },
  {
    name: "GitHub Copilot",
    desc: "AI coding assistant",
    img: "image/logo.png",
    category: "development",
    link: "https://github.com",
  },
  {
    name: "Replit AI",
    desc: "AI coding platform",
    img: "image/logo.png",
    category: "development",
    link: "https://replit.com",
  },

  {
    name: "Fireflies AI",
    desc: "Meeting notes AI tool",
    img: "image/logo.png",
    category: "productivity",
    link: "https://fireflies.ai",
  },
  {
    name: "Otter AI",
    desc: "AI meeting transcription",
    img: "image/logo.png",
    category: "productivity",
    link: "https://otter.ai",
  },
  {
    name: "Taskade AI",
    desc: "AI task manager",
    img: "image/logo.png",
    category: "productivity",
    link: "https://taskade.com",
  },
  {
    name: "ClickUp AI",
    desc: "AI productivity tool",
    img: "image/logo.png",
    category: "productivity",
    link: "https://clickup.com",
  },
  {
    name: "Motion AI",
    desc: "AI scheduling assistant",
    img: "image/logo.png",
    category: "productivity",
    link: "https://usemotion.com",
  },

  {
    name: "Murf AI",
    desc: "AI voice generator",
    img: "image/logo.png",
    category: "audio",
    link: "https://murf.ai",
  },
  {
    name: "PlayHT",
    desc: "AI text to speech tool",
    img: "image/logo.png",
    category: "audio",
    link: "https://play.ht",
  },
  {
    name: "ElevenLabs",
    desc: "Realistic AI voice generator",
    img: "image/logo.png",
    category: "audio",
    link: "https://elevenlabs.io",
  },
  {
    name: "Soundraw",
    desc: "AI music generator",
    img: "image/logo.png",
    category: "audio",
    link: "https://soundraw.io",
  },
  {
    name: "Boomy",
    desc: "Create music using AI",
    img: "image/logo.png",
    category: "audio",
    link: "https://boomy.com",
  },

  {
    name: "DeepL",
    desc: "AI translation tool",
    img: "image/logo.png",
    category: "writing",
    link: "https://deepl.com",
  },
  {
    name: "Wordtune",
    desc: "Rewrite sentences with AI",
    img: "image/logo.png",
    category: "writing",
    link: "https://wordtune.com",
  },
  {
    name: "Rytr",
    desc: "AI writing assistant",
    img: "image/logo.png",
    category: "writing",
    link: "https://rytr.me",
  },
  {
    name: "Sudowrite",
    desc: "AI creative writing tool",
    img: "image/logo.png",
    category: "writing",
    link: "https://sudowrite.com",
  },
  {
    name: "Writesonic",
    desc: "AI writing and chatbot tool",
    img: "image/logo.png",
    category: "writing",
    link: "https://writesonic.com",
  },
];